### ISSUE TITLE
weird claims

### ISSUE THREAD

**Issue by JazzMaster** [PhileCMS/Phile#282]
you claim pico is dead but its an active project(just pushed v1.0 and I randomly bumped into you,you should be indexed alongside pico during a search) . and although I admire the constant re-forking for spit of linux apps, its completely un necessary and wasteful. the claim simply isnt true. pico is very much still kicking.

To extend pico, you need to yank some php  outside of the content folder and link to it. there are some tweaks to the theme twig or html file. thats about all Ive seen so far. As far as plugins, pico seems to want to break on 'php rewrite of files in ram' for some reason and yall may have similar issues.This makes a slew of php errors when loading plugins.

but the main killer of all of this (and anchor cms) is that you have to be root to install composer and composer, though referenced, is NOT installed in the default installable download package. Thereby you CANT expand it.

The CMS runs ok otherwise.
This is mainly a problem with shared hosts or vpns, as root is not usually given to you. And be honest, its rather rude to demand.Not all people making sites have root of a webserver anyhoo.

So for local installs this might be super gravy, but for places like DreamHost, HOstGator, GoDaddy, etc...installing composer? FORGETTTABOUT it. plugins? FORGETTABOUT it.

everything is php edits by hand in such a case. 

GitHub uses Jekyll of course but someone broke the gem as it were and  I cant seem to 'make' anything from it.(and this IS done locally) In that case, the pico-esque output is just thrown onto the webserver. Jekyll has us beat so far in two ways: commenting and such. Theme-ability.

Grav isnt to my liking yet.

--so I dont yet know where people are making these outrageous claims about.
Im not here to dog you but rather make point.
FFCMS are the SHEET and the BEES KNEES but they are NOT without pitfalls. This is what I have discovered.

**Comment by james2doyle** [comment]
This comment is really about 1.5 years late. At the time when Phile was created, there was significant stagnation in the development of Pico, there was also no comments from the developer or any sign that the development would be moving forward with the feature requests or bug fixes. Then, the project sold to someone else, and development picked up again.

We have talked about setting a download with the full vendor folder in releases. But we haven't had too many reasons to do that since this is a flat file CMS, it makes no sense to run `composer install` on the server. You should **do that locally**, and upload the results, just like how you develop a theme using grunt/gulp/webpack etc.

I am going to close this issue. If you want to post opinions, check out the [Google Plus page](https://plus.google.com/communities/105363272048954062353), or the [Gitter chat](https://gitter.im/PhileCMS/Phile).
