### ISSUE TITLE
Documentation/installation not clear

### ISSUE THREAD

**Issue by okoto** [PhileCMS/Phile#52]
Hi,

i finally installed Phile but i was near dropping it down because i got problem during installing. Hope that helps other and maybe a clearer installation process.

Ok so the first thing i've done is to unpack Phile and try to run http://myserver/path/phile/ and so i've got an error http://myserver/path/phile/setup not found, even if i've activated apache mod_rewrite.

It was not clear that one has to change $config['encryptionKey'] in config.php. I finally got to a page with http://myserver/path/phile/index.php that redirected successfully to http://myserver/path/phile/index.php/setup but not dispaying the setup.md page. So i've figured i has to set up an encryption key by manually opening the setup.md file.

Why not including a .htaccess file to redirect urls to index.php ?

**Comment by 1GNAS** [comment]
Had this issue too. No problems on my dedicated hosting, only on my local WAMP server if I wanted to drop it in a sub folder(not the root folder). Solved it without tampering .htaccess
Had to set the $config['base_url']  to 'http://localhost/phile'
No idea yet on why, but the 'http://' is apparently necessary otherwise the theme might not load even though in the rendered source the link to the css can be correct and it might load directly or lead into a multiple 'localhost/phile' redirections in the url.. a lot of weird stuff, but the 'http://' in front fixes it.
Not a biggie, but I feel like this should be noted in the readme since it still took a little bit of time and confusion since I expected it to work right of the bat like pico.
